[tool.poetry]
name = "time-series-analysis"
version = "0.1.0"
description = ""
authors = ["urf94 <urf@mercuryproject.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<=3.12"
prophet = "^1.1.5"
neuralprophet = "^0.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.packages]
packages = [
    { include = "changepoint_detection" }
]
#include = ["changepoint_detection", "forecast", "another_directory"]