name: Build and Release Package

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: pip install poetry

    - name: Configure build environment
      run: |
        export POETRY_VIRTUALENVS_CREATE=false
        export POETRY_HOME=$(pwd)/.poetry
        export PATH="$POETRY_HOME/bin:$PATH"

    - name: Install dependencies
      run: poetry install --no-dev

    - name: Build package
      run: poetry build

    - name: List build artifacts
      run: ls -al ./dist

    - name: Rename WHL file
      run: |
        WHL_FILE=$(ls ./dist/*.whl)
        echo "Found WHL file: $WHL_FILE"
        if [[ "$WHL_FILE" == *default.dist* ]]; then
          mv "$WHL_FILE" "./dist/time_series_analysis-0.1.4-py3-none-any.whl"
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.URF_PAT }}  # Personal Access Token 사용
      with:
        tag_name: v0.1.4
        release_name: v0.1.4
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/time_series_analysis-0.1.4-py3-none-any.whl
        asset_name: time_series_analysis-0.1.4-py3-none-any.whl
        asset_content_type: application/zip
