name: Build and Release Package

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: pip install poetry

    - name: Get version from pyproject.toml
      id: get_version
      run: |
        VERSION=$(poetry version -s)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Get latest tag
      id: get_latest_tag
      run: |
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

    - name: Compare versions and create tag
      if: steps.get_latest_tag.outputs.LATEST_TAG != 'v${{ env.VERSION }}'
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag v${{ env.VERSION }}
        git push https://${{ secrets.PAT_TOKEN }}@github.com/urf94/time_series_analysis.git v${{ env.VERSION }}

    - name: Install dependencies
      run: poetry install --no-dev

    - name: Build package
      run: poetry build

    - name: Create Release
      if: steps.get_latest_tag.outputs.LATEST_TAG != 'v${{ env.VERSION }}'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: v${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: steps.get_latest_tag.outputs.LATEST_TAG != 'v${{ env.VERSION }}'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/*.whl
        asset_name: time_series_analysis-${{ env.VERSION }}.whl
        asset_content_type: application/zip
